#!/usr/bin/env php
<?php


require_once (__DIR__ . '/../vendor/autoload.php');
require_once (__DIR__ . '/../vendor/frame/Init.php');
define('APP_DIR',__DIR__);
\frame\Base::setAlias('@api', __DIR__ );

$arr_config = frame\helpers\ArrayHelper::merge(
    require(__DIR__ . '/config/main.php'),
    require (__DIR__ . '/config/config.php'),
    [
        'id' => 'console',
        'basePath' => __DIR__ . '/api',
        'controllerNamespace' => 'api\timer',
    ]
);

$application = new \frame\console\Application($arr_config);

$exitCode = $application->run();
exit($exitCode);
